### ISSUE TITLE
Localhost refused to connect on port 8501

### ISSUE THREAD

**Issue by arun-gupta** [rubra-ai/rubra#100]
Tried to follow the Getting Started guide:

```
arungupt@Aruns-MBP-67758 ~ %curl -sfL https://get.rubra.ai | sh -s -- start
arungupt@Aruns-MBP-67758 ~ %
```

localhost:8501 says `localhost refused to connect`

Configuration: Apple M1 Max, 64 GB, Sonoma 14.3.1

Do I need to have Docker Engine running? Are there more prereqs? Where can I see error logs?

**Comment by sanjay920** [comment]
hi Arun,

The quickstart script outputs logs to your terminal when you run it, like:
```
[INFO] Detecting system information...
[INFO] Shell: /bin/zsh
[INFO] Operating System: Darwin
[INFO] Kernel Version: 23.2.0
[INFO] Architecture: arm64
[INFO] Hostname: Sanjays-MBP.attlocal.net
[INFO] Processor Information:
arm
[INFO] Memory Information:
Pages free:                               10471.
[INFO] Disk Usage Information:
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   1.8Ti   9.8Gi   984Gi     1%    394k  4.3G    0%   /
[INFO] Checking for hardware acceleration...
[INFO] Apple Metal supported GPU detected
[INFO] rubra.llamafile already exists, skipping download.
[INFO] Executing rubra.llamafile with -c 16000
[INFO] rubra.llamafile is running with PID: 50605
[INFO] Checking if local model is ready
[WARN] Local model is not ready yet, retrying in 5 seconds...
```

Can you post here what that output looks like?

The pre-reqs are posted here: https://docs.rubra.ai/installation/prerequisites

**Comment by arun-gupta** [comment]
As shown above, the command did not output anything at all. Since then, I've now started Docker Engine:

```
arungupt@Aruns-MBP-67758 ~ %docker --version
Docker version 24.0.2, build cb74dfc
```

Docker Compose is there:

```
arungupt@Aruns-MacBook-Pro-67758 ~ %docker-compose --version
Docker Compose version v2.18.1
```

Running the command again does not produce any output again:

```
arungupt@Aruns-MBP-67758 ~ %curl -sfL https://get.rubra.ai | sh -s -- start
arungupt@Aruns-MBP-67758 ~ %
```

Any idea why the output logs may not be printing?

**Comment by sanjay920** [comment]
Given that you're not seeing any output from the script, which is unexpected, let's try a few steps to diagnose and possibly resolve the issue:

1. **Download the script using `curl`** and save it to a file:
   ```bash
   curl -sfL https://get.rubra.ai -o rubra_install.sh
   ```

Verify `rubra_install.sh` has contents in it: `cat rubra_install.sh`

If rubra_install.sh is empty, populate it with the contents found in https://get.rubra.ai

2. **Change the script's permissions** to make it executable using `chmod`:
   ```bash
   chmod +x rubra_install.sh
   ```

3. **Execute the script**:
   ```bash
   ./rubra_install.sh start
   ```

Let me know how this goes

**Comment by arun-gupta** [comment]
```
arungupt@Aruns-MBP-67758 ~ %curl -sfL https://get.rubra.ai -o rubra_install.sh
arungupt@Aruns-MBP-67758 ~ %ping get.rubra.ai
PING get.rubra.ai (104.21.74.152): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
^C
--- get.rubra.ai ping statistics ---
14 packets transmitted, 0 packets received, 100.0% packet loss
```

Is there an alternative host?

**Comment by sanjay920** [comment]
All of this work has moved to https://github.com/gptscript-ai/gptscript
