### ISSUE TITLE
Quickstart install fails - no space left on device

### ISSUE THREAD

**Issue by darrenparkinson** [rubra-ai/rubra#111]
Following the [quick start](https://docs.rubra.ai/quickstart) guide fails with the following error:

```sh
1 error occurred:
        * write /var/lib/docker/tmp/GetImageBlob1519069880: no space left on device

[ERROR] Failed to start Docker containers
```

Docker is configured with the following resource allocation:

* CPU Limit: 10
* Memory Limit: 24GB
* Swap: 4GB

The machine is a Macbook Pro with 350GB free space

**Comment by cloudnautique** [comment]
Hi, Docker runs in a VM on the machine and has it's own virtual disk, so even if the host has free space, the VM can run out.

You can do a few things to address disk space, like resizing to something larger, or you can clean up unused images in the Docker app.
