### ISSUE TITLE
AWQ?

### ISSUE THREAD

**Issue by themrzmaster** [rubra-ai/rubra#119]
HI!
WOuld be nice to have AWQ quantization, so we can run on vLLM with a lower end GPU.
Thanks for your work!

**Comment by sanjay920** [comment]
hey @themrzmaster what model are you looking for awq quants? i can get that for you

**Comment by themrzmaster** [comment]
70b would be nice

**Comment by sanjay920** [comment]
@themrzmaster https://huggingface.co/rubra-ai/Meta-Llama-3-70B-Instruct-AWQ

Let me know if you have any problems with it. If it looks good feel free to close this issue.

**Comment by themrzmaster** [comment]
Worked! Thank you!! Any plan on releasing the dataset?
