### ISSUE TITLE
Modifying an assistant doesn't handle files

### ISSUE THREAD

**Issue by cloudnautique** [rubra-ai/rubra#2]
When you modify an assistant, it doesn't remember previously associated files. It also doesn't allow re-uploading them. 

The expectation is that as prompts are being adjusted the files and data it has been associated with would still be used.

**Comment by tybalex** [comment]
PR #92 will fix this.

**Comment by sangee2004** [comment]
Tested on latest builds

Modifying Assistant created with files , does not result in existing files getting deleted
Modifying Assistant lists all existing files associated with the assistant.
Modifying Assistant allows to upload more files/delete existing ones.
There is 1 issue with deleting files which is tracked in https://github.com/rubra-ai/rubra/issues/105
