### ISSUE TITLE
Modifying Assistant results in existing files to be deleted. It should also allow to upload more files/delete existing ones.

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#30]
**Steps to reproduce the problem:**
1. Create an assistant with browser option enabled and upload a file. 
2. Modify this assistant and disable browser option .
3.Notice that existing file is not presented in the `Update Assistant` view.
4. Once this entry is updated , existing files seem to be lost for the assistant.
5. Assistant does not have the "Knowledge" tag anymore 

**Expected Behavior:**
1. Modifying Assistant should not result in existing files to be deleted
2. Also Modifying Assistant should allow to upload more files/delete existing ones.

**Comment by tybalex** [comment]
This will be addressed in PR #92

**Comment by sangee2004** [comment]
Tested on latest builds 

1. Modifying Assistant created with files , does  not result in existing files getting deleted
2. Modifying Assistant lists all existing files associated with the assistant.
3. Modifying Assistant allowa to upload more files/delete existing ones.


There is 1 issue with deleting files which is tracked in https://github.com/rubra-ai/rubra/issues/105
