### ISSUE TITLE
Assistants from previous installs are still listed and usable on fresh installs.

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#38]
**Steps to reproduce the problem:**
1. Install rubra - curl -sfL Ihttps://raw.githubusercontent.com/acorn-io/rubra/main/quickstart.sh | sh -s -- start
2. Create assistants.
3. Uninstall rubra
```
curl -sfL https://raw.githubusercontent.com/acorn-io/rubra/main/quickstart.sh | sh -s -- stop
rm -r ~/.rubra
```
4. Install rubra - curl -sfL Ihttps://raw.githubusercontent.com/acorn-io/rubra/main/quickstart.sh | sh -s -- start
5. After installation, notice that all the assistants. created in step2 are still present  and usable.

**Expected Behavior:**
1. There should be no assistants available on installs done after uninstall of rubra

Related issue - https://github.com/acorn-io/rubra/issues/32

**Comment by sangee2004** [comment]
Following steps needed to be done manually to clear all assistants from previous installs:
```
docker volume rm  rubra_mongodb
```

**Comment by sanjay920** [comment]
This should be addressed in https://github.com/rubra-ai/rubra/commit/5dc8c89f4a6be74ffca2ab5cc68a353eb8c3285d

There is now an easy way to delete data and do a full uninstall. 

Delete data: `curl -sfL https://get.rubra.ai | sh -s -- delete`
Full uninstall: `curl -sfL https://get.rubra.ai | sh -s -- uninstall`

**Comment by tybalex** [comment]
can we close this issue?

**Comment by sangee2004** [comment]
Assistants from previous installs are not seen when deleting data / uninstalling before the app is started again.

```
Delete data: curl -sfL https://get.rubra.ai | sh -s -- delete
Full uninstall: curl -sfL https://get.rubra.ai | sh -s -- uninstall
```
