### ISSUE TITLE
Feature Request: LiteLLM for backend abstraction

### ISSUE THREAD

**Issue by dannysemi** [rubra-ai/rubra#68]
You could use your current backend as defaults, but also allow for other backend options to be easily configured. The library supports tons of apis and local options.

[https://github.com/BerriAI/litellm](https://github.com/BerriAI/litellm)

**Comment by sanjay920** [comment]
@dannysemi thanks for the input!

This is on our todo list. We will add more backends up as we start testing the local tools on them

**Comment by sanjay920** [comment]
All of this work has moved to https://github.com/gptscript-ai/gptscript
Rubra will be for tool calling LLMs coming out in a few days
