### ISSUE TITLE
Create macOS dmg and bundle

### ISSUE THREAD

**Issue by cloudnautique** [rubra-ai/rubra#70]
Create a macOS dmg and app bundle to install and manage Rubra.

The App is built with Tauri, and replaces the Quickstart script experience.
The app:

1. Checks for docker and docker-compose commands to be available. If not, it shows a link to the Docker Desktop install page.
2. sets up ~/.rubra directory and populates a docker-compose.yml, embedEtcd.yaml, llm-config.yaml
4. Downloads the Model and shows a status bar while downloading. Once complete, the ~/.rubra/rubra.llamafile will be present.
5. Docker images will use tagged images. The tags will be vX.X.X the same release they are downloaded from.
6. When starting for the first time, the Start Rubra button is grayed out. Once the model and containers have started there will be a stop rubra and launch UI button.
7. closing the window will keep the app and model running.
8. You can use the sys tray icon to get back to the app or launch the UI.
9. the Command-Q button will quit the App and stop all containers/model from running.

You can verify the model is running by looking for .ape-10 processes in activity monitor or ps. There should only be one.

**Comment by sangee2004** [comment]
Able to install rubra `v0.0.2` successfully from the dmg file - https://github.com/rubra-ai/rubra/releases/download/v0.0.2/Rubra_0.0.2_universal.dmg.

Issues (bugs and improvements) found when testing the installer are tracked as separate issues -
https://github.com/rubra-ai/rubra/issues?q=is%3Aopen+is%3Aissue+label%3AInstall
