### ISSUE TITLE
Provide a way to uninstall rubra.

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#73]
Provide a way to uninstall rubra.

Currently I have to do the following steps to uninstall rubra.
```
curl -sfL https://get.rubra.ai/ | sh -s -- stop 
 rm -r ~/.rubra
docker volume rm  rubra_mongodb rubra_milvus rubra_etcd
```

We need to support uninstall for cli and  dmg install.

**Comment by sanjay920** [comment]
https://github.com/rubra-ai/rubra/commit/5dc8c89f4a6be74ffca2ab5cc68a353eb8c3285d should resolve this

https://docs.rubra.ai/installation/uninstall

**Comment by tybalex** [comment]
should we close this issue now?
