### ISSUE TITLE
Not able to launch Rubra app from tool bar once the app window is closed.

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#77]
dmg used - `v0.0.2`

**Steps to reproduce the problem:**
1. lnstall app.
2. Once installed , close the Rubra app page (using "x").
3. Try to click on the `Rubra` app in the bottom tool bar.
4. Nothing happens.
Note - Clicking on `Rubra` app in Menu bar (in the top) still works.

The only way to make it start working is to use the "quit" option and relaunch.

**Comment by cloudnautique** [comment]
Were you able to use the system tray Icon?

**Comment by sangee2004** [comment]
Yes. I am able to launch Dashboard/UI using the Rubra app in Menu bar (in the top right side) .

**Comment by cloudnautique** [comment]
This is a limitation of the Tauri framework. It is currently not a supported feature.

Need to put this on hold until the framework has better support.
