### ISSUE TITLE
Rubra chat with default model (custom) does not return results from browser

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#79]
**Steps to reproduce the problem:**
1. Installed Rubra 0.2.0 using dmg.
2. Use Chat window , to ask "Who won super bowl 2024?"

<img width="784" alt="Screen Shot 2024-02-17 at 9 15 38 AM" src="https://github.com/rubra-ai/rubra/assets/122560863/aa76d8b3-8cbb-48b4-a6c4-902aa35c8a15">

Browser is not enabled for "custom" model.

**Note** - If i create my own assistant with browser option enabled, then i see browser integration working as expected.

**Comment by sanjay920** [comment]
@sangee2004 you're chatting with a `Model`, not an assistant. To get web browsing capability, use/create an `Assistant` and chat with that.

Marking this as closed.
