### ISSUE TITLE
When modifying the assistant, getting a list of the associated documents in its 'context'

### ISSUE THREAD

**Issue by sanjay920** [rubra-ai/rubra#82]

**Comment by tybalex** [comment]
will be addressed in #92

**Comment by sangee2004** [comment]
Tested on latest builds

Modifying Assistant created with files , does not result in existing files getting deleted
Modifying Assistant lists all existing files associated with the assistant.
Modifying Assistant allowa to upload more files/delete existing ones.
There is 1 issue with deleting files which is tracked in https://github.com/rubra-ai/rubra/issues/105
