### ISSUE TITLE
Not able to see "Welcome Assistant"

### ISSUE THREAD

**Issue by sangee2004** [rubra-ai/rubra#85]
Build from `https://get.rubra.ai`
**Steps to reproduce the problem**
1. Uninstall/delete existing rubra installs ( `curl -sfL https://get.rubra.ai | sh -s -- uninstall` or `curl -sfL https://get.rubra.ai | sh -s -- delete`
2. Install rubra
`curl -sfL https://get.rubra.ai | sh -s -- start`

Once app is installed successfully and UI is launched , notice that the "Welcome Assistant" is not available as an option in the "Select a Model or an Assistant" in `Chat` window.

**Expected Behavior:**
"Welcome Assistant" should be available on install.

**Comment by sanjay920** [comment]
```

**Comment by tybalex** [comment]
This should be fixed in #93

**Comment by sangee2004** [comment]
When deploying with https://github.com/rubra-ai/rubra/pull/93 , I see the following errors and UI fails to launch

```
litellm             | LiteLLM Proxy: INITIALIZING LITELLM CALLBACKS!
litellm             | callback: <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x2aaab30c7a60>
litellm             | callback: <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x2aaab30c7a90>
litellm             | callback: cache
litellm             | callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x2aaab33a6970>>
litellm             | callback: <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x2aaab30c7ac0>
litellm             | callback: <bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x2aaab35f2c70>>
litellm             | INFO:     127.0.0.1:35230 - "GET /health HTTP/1.1" 200 OK
litellm             | INFO:     127.0.0.1:60902 - "GET /health HTTP/1.1" 200 OK
litellm             | INFO:     127.0.0.1:39662 - "GET /health HTTP/1.1" 200 OK
dependency failed to start: container litellm is unhealthy
```

**Comment by tybalex** [comment]
the health check of litellm could be very slow. So I change the timeout to 30s.

**Comment by sangee2004** [comment]
With latest builds, I am able to see "Welcome Assistant"  available on fresh installs.
