### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by arun-gupta** [rubra-ai/rubra#99]
"installation section" link on https://docs.rubra.ai/quickstart is giving 404. It is linking to https://docs.rubra.ai/getting-started/installation and should instead be https://docs.rubra.ai/installation/

**Comment by sanjay920** [comment]
https://github.com/rubra-ai/rubra/commit/5d4096768105871a42a6fe2dbdb83bb911896987 resolves this. thanks for the catch!
